version: "3.8"

services:
  app:
    container_name: app
    image: jaderh/docker-nginx-php-supervisor:8.3
    ports:
      - 80:80
      - 443:443
      - 8787:8787
      - 8585:8585
      # - 9501:9501
    environment:
      TZ: Asia/Shanghai
    volumes:
      # - /Users/jade/Jader/Code/:/webser/www/
      - /Users/jade/Jader/Code/hyperf-test:/webser/www/hyperf-test
      - /Users/jade/Jader/Code/webman-test:/webser/www/webman-test
      - /Users/jade/Jader/Code/laravel-test:/webser/www/laravel-test
      - /Users/jade/Jader/Code/thinkphp-test:/webser/www/thinkphp-test
      - /Users/jade/Jader/Custom/PsyWeb:/webser/www/psy-test
      # - ./config/cl-mall.conf:/etc/nginx/conf.d/cl-mall.conf
      - ./config/dev.conf:/etc/nginx/conf.d/dev.conf
      # - ./config/php-monitor.conf:/etc/nginx/conf.d/php-monitor.conf
      - ./config/supervisor-php.ini:/etc/supervisor.d/supervisor-php.ini
    networks:
      server_network:
        ipv4_address: 172.16.120.11

  db:
    container_name: db
    image: mysql:5.7.40
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - 3306:3306
    volumes:
      - /Users/jade/Jader/MysqlData/57:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: Jade@1994
      TZ: Asia/Shanghai
    networks:
      server_network:
        ipv4_address: 172.16.120.13

networks:
  server_network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.16.120.0/24
          gateway: 172.16.120.1